# artifact, this is no linger needed.

# [manifest]
# version = "0.1.0"
# dump_lua = true
# priority = 0

# [[patches]]
# [patches.pattern]
# target = "functions/common_events.lua"
# pattern = " return boss"
# position = "before"
# match_indent = true
# payload = '''
#    G.GAME.willatro_bosses = eligible_bosses
# '''